HathorNetwork/hathor-wallet-headless

package-lock.json
package.json

Babel 7.8.3 has a bug and does not work with Node 13.2. Check it out here: https://github.com/babel/babel/issues/11216#issuecomment-595323314

fix: Update babel to 7.8.4

---

index.js
package-lock.json
package.json

feat: creating connection to be used in the wallet without sharing between them

---

README.md
api-docs.js
index.js
package-lock.json
package.json

Only need to update the wallet lib version when it's released.
Wallet lib PR: https://github.com/HathorNetwork/hathor-wallet-lib/pull/78

feat: add new endpoint to send transactions with many outputs

---

QA.md

[Rendered](https://github.com/HathorNetwork/hathor-wallet-headless/blob/chore/add-qa/QA.md)

chore: add QA file

---

index.js
package-lock.json
package.json

It also updates the wallet lib to a version which makes the transaction mining for the testnet to work

feat: add API to get all addresses of a wallet

---

api-docs.js
index.js

Design: https://github.com/HathorNetwork/hathor-wallet-lib/issues/137

feat: add change address as optional parameter in simple-send-tx and send-tx

---

api-docs.js
index.js
package-lock.json
package.json

- New endpoint GET `/wallet/utxo-filter`
Return utxos and some helpful information regarding it.
- New endpoint POST `/wallet/utxo-consolidation`
Consolidates utxos to a given address.
- Update `api-docs`

feat: utxo consolidation

---

config.js.template
index.js
logger.js
package-lock.json
package.json
version.js

```bash
$ npm start
> hathor-wallet-headless@0.6.0 start /Users/msbrogli/Hathor/hathor-wallet-headless
> babel-node index.js
2021-02-26T06:23:39.033Z [wallet] info: Starting Hathor Wallet... {"wallet":"0.6.0","version":"v12.18.0","platform":"darwin","pid":15931}
2021-02-26T06:23:39.035Z [wallet] info: Set GAP LIMIT to 20
2021-02-26T06:23:39.041Z [wallet] info: Listening on localhost:8000...
2021-02-26T06:23:46.593Z [wallet] info: Wallet started with wallet id 123. Full-node info:  {"version":"0.38.0","network":"mainnet","min_weight":14,"min_tx_weight":14,"min_tx_weight_coefficient":1.6,"min_tx_weight_k":100,"token_deposit_percentage":0.01,"reward_spend_min_blocks":300,"max_number_inputs":255,"max_number_outputs":255}
2021-02-26T06:23:46.596Z [http] info: 127.0.0.1 - - …
```

feat: Add logging configuration

---

package.json
src/api-docs.js
src/index.js

1. Fix path to call `generate_words` script
2. Fix version in api docs file
3. Add `change_address` to `send-tx` parameters schema

fix: small fixes

---

__tests__/__fixtures__/http-fixtures.js
__tests__/send-tx.test.js
__tests__/tx-history.test.js
package-lock.json
package.json
src/index.js

refactor: make wallet headless compatible with lib again

---

__tests__/send-tx.test.js
__tests__/simple-send-tx.test.js
package-lock.json
package.json
src/api-docs.js
src/index.js

refactor: adapting wallet facade calls to use new method signatures and returns

---

__tests__/create-nft.test.js
package-lock.json
package.json
src/api-docs.js
src/index.js

- There must be a new API to create an NFT.

feat: add new API to create NFT

---

.github/workflows/docker.yml
README.md

- We should build and push Docker images to Dockerhub every time a tag is created

chose: push docker images to DockerHub

---

.github/workflows/docker.yml
README.md
package-lock.json
package.json

* https://github.com/HathorNetwork/hathor-wallet-headless/pull/128

Release version v0.9.1

---

package-lock.json
package.json

chore: bump t0 v0.11.0 and upgrade wallet-lib to v0.27.0

---

.dockerignore
config.js.docker
package-lock.json
package.json

Release v0.11.0

---

package-lock.json
package.json

chore: bump version v0.11.1

---

QA.md

- QA should state the right testnet url

fix: testnet url on QA

---

package-lock.json
package.json

- https://github.com/HathorNetwork/hathor-wallet-headless/pull/181
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/171
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/164
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/174
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/156
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/175

bump: v0.12.0

---

package-lock.json
package.json

chore: bump version to v0.13.0

---

__tests__/address-info.test.js
__tests__/address.test.js
__tests__/addresses.test.js
__tests__/balance.test.js
__tests__/create-nft.test.js
__tests__/create-token.test.js
__tests__/create-tx-proposal.test.js
__tests__/decode.test.js
__tests__/features.test.js
__tests__/get-my-signatures.test.js
__tests__/melt-tokens.test.js
__tests__/mint-tokens.test.js
__tests__/multisig-pubkey.test.js
__tests__/send-tx.test.js
__tests__/simple-send-tx.test.js
__tests__/start.test.js
__tests__/status.test.js
__tests__/test-utils.js
__tests__/transaction.test.js
__tests__/tx-history.test.js
__tests__/tx-proposal-sign-and-push.test.js
__tests__/tx-proposal-sign.test.js
__tests__/utxo.test.js
package.json
setupTests.js

This fixes the intermittent errors on the start tests (described here #191) 
- Each tests suite should have it's own individual wallet id so they can all be independent.

tests: individual wallets for each test

---

__tests__/integration/multisig.test.js
package-lock.json
package.json
src/controllers/wallet/tx-proposal.controller.js

Fix problems described on #191

tests: do not skip multisig tests

---

__tests__/test-utils.js

- Remove unused variable from test-utils

chore: remove unused variable

---

src/index.js

- Add warning that changing user agent might break other services

chore: add warning in the user agent set not to change it

---

src/api-docs.js

- Add seed as a parameter for `/start` on api-docs

chore: add seed on api-docs

---

package-lock.json
package.json

chore: bump version to v0.14.0

---

config.js.docker
package-lock.json
package.json

Release v0.14.1

---

package-lock.json
package.json

bump: v0.15.0

---

package-lock.json
package.json
src/api-docs.js

chore: bump version to v0.16.0

---

.github/workflows/docker.yml
RELEASING.md
__tests__/__fixtures__/http-fixtures.js
__tests__/configuration_string.test.js
__tests__/integration/configuration-string.test.js
__tests__/integration/create-nft.test.js
__tests__/integration/create-token.test.js
__tests__/integration/utils/test-utils-integration.js
__tests__/test-utils.js
package-lock.json
package.json
src/api-docs.js
src/controllers/index.controller.js
src/controllers/wallet/wallet.controller.js
src/index.js
src/routes/index.routes.js

Release v0.16.0

---

__tests__/__fixtures__/http-fixtures.js
__tests__/integration/transaction.test.js
__tests__/integration/utils/test-utils-integration.js
__tests__/test-utils.js
__tests__/transaction.test.js
src/api-docs.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/wallet.routes.js

- Create new API to get the number of blocks confirming a tx
Closes https://github.com/HathorNetwork/hathor-wallet-headless/issues/228

feat: add new API to get number of blocks confirming a tx

---

__tests__/integration/multisig.test.js
__tests__/integration/utils/test-utils-integration.js
package-lock.json
package.json
src/controllers/wallet/p2sh/tx-proposal.controller.js

fix: set store before creating proposal

---

package-lock.json
package.json
src/api-docs.js

chore: bump v0.17.0

---

__tests__/__fixtures__/http-fixtures.js
__tests__/integration/multisig.test.js
__tests__/integration/transaction.test.js
__tests__/integration/utils/test-utils-integration.js
__tests__/test-utils.js
__tests__/transaction.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/wallet.routes.js

Release v0.17.0

---

__tests__/atomic-swap/tx-proposal-create.test.js
__tests__/integration/atomic-swap.test.js
src/controllers/wallet/atomic-swap/tx-proposal.controller.js
src/schemas.js

- Apply changes on create atomic-swap tx-proposal api
- Change tests

feat: change atomic-swap api parameters

---

package-lock.json
package.json
src/api-docs.js

chore: bump version 0.18.0

---

src/api-docs.js

- Update api-docs with atomic-swap routes

chore: atomic swap api docs

---

.eslintrc
ATOMIC_SWAP.md
__tests__/atomic-swap/get-my-signatures.test.js
__tests__/atomic-swap/locked-utxos.test.js
__tests__/atomic-swap/p2sh.test.js
__tests__/atomic-swap/sign-and-push.test.js
__tests__/atomic-swap/sign.test.js
__tests__/atomic-swap/tx-proposal-create.test.js
__tests__/decode.test.js
__tests__/integration/atomic-swap.test.js
__tests__/p2sh/tx-proposal-create.test.js
__tests__/p2sh/tx-proposal-get-my-signatures.test.js
__tests__/p2sh/tx-proposal-sign-and-push.test.js
__tests__/p2sh/tx-proposal-sign.test.js
package-lock.json
package.json
scripts/helpers/wallet-precalculation.helper.js
setupTests-integration.js
src/api-docs.js
src/controllers/wallet/atomic-swap/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/atomic-swap/atomic-swap.routes.js
src/routes/wallet/atomic-swap/tx-proposal.routes.js
src/routes/wallet/wallet.routes.js
src/schemas.js
src/services/atomic-swap.service.js

Release v0.18.0

---

ATOMIC_SWAP.md

- Remove a parameter from the docs that does not exist anymore.

chore: remove isComplete from get-my-signatures response

---

__tests__/integration/readonly-wallet.test.js
__tests__/push-tx-hex.test.js
__tests__/send-tx.test.js
__tests__/tx-proposal/add-signatures.test.js
__tests__/tx-proposal/build-tx.test.js
__tests__/tx-proposal/get-wallet-inputs.test.js
__tests__/tx-proposal/getInputData.test.js
__tests__/tx-proposal/push-tx-hex.test.js
package-lock.json
package.json
scripts/helpers/wallet-precalculation.helper.js
src/api-docs.js
src/controllers/index.controller.js
src/controllers/wallet/tx-proposal/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/helpers/tx.helper.js
src/helpers/wallet.helper.js
src/middlewares/xpub-error-handler.middleware.js
src/routes/index.routes.js
src/routes/wallet/tx-proposal/tx-proposal.routes.js
src/routes/wallet/wallet.routes.js
src/schemas.js

- Implement the [design](https://github.com/HathorNetwork/internal-issues/issues/130)
- Create an error handler for the write protection error.
- Create endpoints for creating and pushing transactions from readonly wallets.

feat: readonly wallets

---

.github/workflows/codeql.yml
Makefile
src/controllers/index.controller.js
src/controllers/wallet/wallet.controller.js
src/logger.js
src/middlewares/wallet.middleware.js
src/services/wallets.service.js

This is the same as https://github.com/HathorNetwork/hathor-wallet-headless/pull/249, but with the errors and warnings fixed.
Fixed errors:
- https://github.com/HathorNetwork/hathor-wallet-headless/security/code-scanning/4
- https://github.com/HathorNetwork/hathor-wallet-headless/security/code-scanning/5
- https://github.com/HathorNetwork/hathor-wallet-headless/security/code-scanning/33, in this case it seems the alert didn't detect my fix of using a `Map` instead of an object, which is what it suggest to fix it. I think we should now dismiss it, but I didn't do so yet just to let reviewers think about it as well.
- https://github.com/HathorNetwork/hathor-wallet-headless/security/code-scanning/31
Some errors were dismissed as false positives instead of fixed (the dismissal reason is added …

ci: Add CodeQL workflow

---

package-lock.json
package.json
src/api-docs.js

* chore: bump wallet lib to v0.42.1
* chore: bump headless to v0.19.1

Release v0.19.1

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.19.2

---

__tests__/send-tx.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/wallet.controller.js

Release v0.19.2

---

src/services/notification.service.js

- Fix a typo in the update-tx event name

fix: plugin update tx typo

---

PLUGIN.md
__tests__/__fixtures__/http-fixtures.js
package-lock.json
package.json
scripts/get_xpub_from_seed.js
src/api-docs.js
src/plugins/hathor_websocket.js
src/services/notification.service.js

Release v0.19.3

---

package-lock.json
package.json
src/api-docs.js

-  https://github.com/HathorNetwork/hathor-wallet-headless/pull/275
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/280
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/279

bump: v0.20.0

---

__tests__/integration/melt-tokens.test.js
__tests__/integration/mint-tokens.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/wallet.routes.js

- Add new parameter to choose new created authority address for mint and melt APIs

feat: add new parameter to choose authority address for mint/melt APIs

---

package-lock.json
package.json
src/api-docs.js

- Bump package to version v0.21.0

chore: bump to v0.21.0

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.21.0-rc1

---

__tests__/atomic-swap/service.test.js
__tests__/atomic-swap/tx-proposal-create.test.js
src/api-docs.js
src/controllers/wallet/atomic-swap/tx-proposal.controller.js
src/errors.js
src/helpers/wallet.helper.js
src/schemas.js
src/services/atomic-swap.service.js

- Adds the option to `update` a proposal with the Atomic Swap Service

feat: Swap service `update` partialTx

---

.github/workflows/docker.yml
package.json
scripts/github/docker.py

- Create a script to build the docker tags
- Consider release candidate tags where we do not want to update the `lastest` tag

chore: create docker tag script

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.22.0-rc1

---

.github/workflows/docker.yml
package-lock.json
package.json
scripts/github/docker.py
src/api-docs.js

Release version v0.22.0-rc1

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.22.0-rc2

---

Dockerfile
package-lock.json
package.json
src/api-docs.js

Release version v0.22.0-rc2

---

package-lock.json
package.json
src/api-docs.js

chore: bump version 0.22.0-rc3

---

__tests__/integration/multisig.test.js
__tests__/integration/utils/test-utils-integration.js
__tests__/test-utils.js
package-lock.json
package.json
scripts/github/docker.py
setupTests.js
src/api-docs.js

Release version v0.22.0-rc3

---

__tests__/__fixtures__/http-fixtures.js
__tests__/mint-tokens.test.js
__tests__/p2sh/tx-proposal-mint-tokens.test.js
__tests__/p2sh/tx-proposal-new-token.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/routes/wallet/p2sh/tx-proposal.routes.js

- add create-token endpoint for p2sh wallet: `/wallet/p2sh/tx-proposal/create-token`
- add mint-tokens endpoint for p2sh wallet: `/wallet/p2sh/tx-proposal/mint-tokens`
Closes https://github.com/HathorNetwork/hathor-wallet-headless/issues/301

feat: add create-token and mint-token endpoint for p2sh wallet

---

__tests__/__fixtures__/http-fixtures.js
__tests__/p2sh/tx-proposal-melt-tokens.test.js
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/routes/wallet/p2sh/tx-proposal.routes.js

- add melt-tokens endpoint for p2sh wallet: /wallet/p2sh/tx-proposal/melt-tokens
Closes: https://github.com/HathorNetwork/hathor-wallet-headless/issues/303

feat: add melt-tokens endpoint for p2sh wallet

---

__tests__/__fixtures__/http-fixtures.js
__tests__/decode.test.js
__tests__/p2sh/tx-proposal-melt-tokens.test.js
__tests__/p2sh/tx-proposal-new-token.test.js
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/helpers/tx.helper.js
src/routes/wallet/p2sh/tx-proposal.routes.js

- extende the decode endpoint `/wallet/decode` with transaction, input, output and balance metadatas
Closes: https://github.com/HathorNetwork/hathor-wallet-headless/issues/304

chore: add metadata to decode endpoint

---

package-lock.json
package.json

chore: bump wallet-lib to rc8

---

__tests__/__fixtures__/http-fixtures.js
__tests__/decode.test.js
__tests__/integration/atomic-swap.test.js
__tests__/integration/multisig.test.js
__tests__/integration/utils/test-utils-integration.js
__tests__/integration/utils/wallet-helper.js
__tests__/mint-tokens.test.js
__tests__/p2sh/tx-proposal-melt-tokens.test.js
__tests__/p2sh/tx-proposal-mint-tokens.test.js
__tests__/p2sh/tx-proposal-new-token.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/helpers/tx.helper.js
src/routes/wallet/p2sh/tx-proposal.routes.js

Release 0.22.0-rc4

---

package-lock.json
package.json
src/api-docs.js

chore: bump to v0.22.0-rc5

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.22.0

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.22.0-rc6

---

src/patch.js
src/routes/index.routes.js
src/routes/wallet/atomic-swap/atomic-swap.routes.js
src/routes/wallet/atomic-swap/tx-proposal.routes.js
src/routes/wallet/p2sh/p2sh.routes.js
src/routes/wallet/p2sh/tx-proposal.routes.js
src/routes/wallet/tx-proposal/tx-proposal.routes.js
src/routes/wallet/wallet.routes.js

- Handle async rejections on async handlers using express middlewares

fix: patch the express router to handle async errors

---

package-lock.json
package.json
src/api-docs.js
src/patch.js
src/routes/index.routes.js
src/routes/wallet/atomic-swap/atomic-swap.routes.js
src/routes/wallet/atomic-swap/tx-proposal.routes.js
src/routes/wallet/p2sh/p2sh.routes.js
src/routes/wallet/p2sh/tx-proposal.routes.js
src/routes/wallet/tx-proposal/tx-proposal.routes.js
src/routes/wallet/wallet.routes.js

Release version v0.22.0

---

src/api-docs.js

- Add reload-config to api-docs

docs: reload-config api-docs

---

package-lock.json
package.json
src/api-docs.js

- Bump wallet to version v0.23.0

Chore/bump v0.23.0

---

.github/workflows/codeql.yml
.github/workflows/docker.yml
.github/workflows/integration-test.yml
.github/workflows/lint.yml
.github/workflows/main.yml
scripts/github/docker.py

- Change the target branches of the github actions to include the new branches of the new release process

chore: CI changes for the new release process

---

__tests__/__fixtures__/http-fixtures.js
__tests__/__fixtures__/settings-fixture.js
__tests__/healthcheck.test.js
__tests__/integration/send-tx.test.js
__tests__/test-utils.js
src/api-docs.js
src/controllers/healthcheck/healthcheck.controller.js
src/helpers/constants.js
src/helpers/healthcheck.helper.js
src/routes/healthcheck/healthcheck.routes.js
src/routes/index.routes.js
src/routes/wallet/wallet.routes.js
src/services/healthcheck.service.js

[//]: # (This should be discussed in the daily meeting)
[//]: # (Remember to bump the version to the next release candidate after this is merged)
Start the release candidate process for version `v0.23.1-rc1`.
This PR will merge any changes on `master` into `release-candidate` branch.

release-candidate: v0.23.1-rc1

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.23.1-rc1

---

.github/workflows/docker.yml
scripts/github/docker.py

- Build staging images on any push to master

chore(ci): build staging image on push to master

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.23.1-rc2

---

Dockerfile
package-lock.json
package.json

- Use a multistage dockerfile
- Move babel to dev dependency
- Use production node environment
- lock wallet-lib version

feat: multistage dockerfile

---

package-lock.json
package.json
src/api-docs.js

chore: bump version v0.23.1

---

package-lock.json
package.json

- Merge release v0.23.1 with master fixing conflicts

chore: fix release conflicts

---

__tests__/integration/create-token.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/wallet.routes.js

- Add support for multiple data outputs in the create token API

feat: add support for multiple data outputs in the create token API

---

package-lock.json
package.json

- Bump headless to v0.24.0-rc1

chore: bump version to v0.24.0-rc1

---

package-lock.json
package.json

chore: bump package version to v0.24.0

---

codecov.yml

- Update default branch in the codecov conf file

chore: update codecov branch to master

---

package.json
scripts/create-hsm-wallet.js

- The script should create a new key on the HSM with an `xPriv` for the headless to use

Feat: Script to create new HSM wallet

---

__tests__/plugins/debug_plugin.test.js
src/index.js
src/plugins/child.js
src/plugins/hathor_debug.js

- setup config on plugin startup

fix: setup settings for plugins

---

package-lock.json
package.json

chore: bump v0.25.0-rc1

---

package-lock.json
package.json

chore: bump v0.25.0

---

package-lock.json
package.json
src/plugins/hathor_debug.js
src/plugins/hathor_rabbitmq.js
src/plugins/hathor_sqs.js
src/plugins/hathor_websocket.js

- Upgrades `yargs` from `16.6.20` to the latest stable version `17.7.2`
The breaking changes mentioned in [the v17 release notes](https://github.com/yargs/yargs/releases/tag/v17.0.0) do not impact this application.
This dependency is used only on the plugins, and its usage is already being properly validated on their unit tests.

chore: Upgrades `yargs`

---

.eslintrc
__tests__/__fixtures__/http-fixtures.js
__tests__/healthcheck.test.js
__tests__/test-utils.js
package-lock.json
package.json
src/services/healthcheck.service.js

Depends on: https://github.com/HathorNetwork/hathor-wallet-lib/pull/608
- We should consult hathor-core's health endpoint to build our own health response.

chore: use hathor-core health endpoint

---

package-lock.json
package.json

- Bump version to v0.26.0-rc.1

bump: v0.26.0-rc.1

---

package-lock.json
package.json

- Bump version to v0.26.0 for the new release

bump: v0.26.0

---

package-lock.json
package.json
src/controllers/hsm/hsm.controller.js
src/services/hsm.service.js
src/services/wallets.service.js

- Allow headless to sign nano contract transactions

feat: hsm integration for nano contracts

---

package-lock.json
package.json

chore: bump v0.27.0-rc1

---

config.js.docker

- Add the HSM config options on the docker config file

feat: hsm docker config

---

package-lock.json
package.json

chore: bump v0.28.0-rc.1

---

package-lock.json
package.json

bump-v0.28.0

---

docs/README.md
docs/hsm.md

- Document how to use the HSM integration

docs: hsm docs

---

__tests__/integration/melt-tokens.test.js
__tests__/integration/mint-tokens.test.js
__tests__/melt-tokens.test.js
__tests__/mint-tokens.test.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/wallet.controller.js
src/routes/wallet/wallet.routes.js

- Include options to add data output on the headless

feat: data token admin

---

package-lock.json
package.json

chore: bump v0.29.0-rc.1

---

package-lock.json
package.json

chore: bump-v0.29.0

---

.github/workflows/integration-test.yml
.github/workflows/main.yml

- The integration tests should upload its results to CodeCov
- Style improvements on the workflow files

fix: codecov on integration tests

---

__tests__/atomic-swap/atomic-swap-service.test.js
__tests__/atomic-swap/fetch-from-service.test.js
__tests__/atomic-swap/tx-proposal-create.test.js
__tests__/integration/configuration/test-constants.js
__tests__/integration/create-token.test.js
__tests__/tx-proposal/build-tx.test.js
package-lock.json
package.json
src/controllers/wallet/atomic-swap/tx-proposal.controller.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/helpers/tx.helper.js

- Upgrade wallet-lib to v1.8.0
- Fix breaking changes

chore: upgrade wallet-lib v1.8.0

---

__tests__/integration/lock.test.js
__tests__/simple-send-tx.test.js
src/controllers/index.controller.js
src/controllers/wallet/atomic-swap/tx-proposal.controller.js
src/controllers/wallet/nano-contracts.controller.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/lock.js
src/services/wallets.service.js

- `SENT_TX` lock should be applied on a per-wallet basis

feat: per wallet lock

---

package-lock.json
package.json

- Bump wallet version v0.30.0-rc.1

chore: bump version v0.30.0-rc.1

---

package-lock.json
package.json

[//]: # (This should be discussed in the daily meeting)
[//]: # (Remember to bump the version to the next release candidate after this is merged)
Include `v0.30.0-rc.1` version bump since it was made directly on master.

fix: include v0.30.0-rc.1 bump

---

package-lock.json
package.json

chore: bump v0.30.0

---

package-lock.json
package.json

- Sync release v0.30.0 changes to master

Chore/sync release v0.30.0

---

.github/workflows/codeql.yml
.github/workflows/docker.yml
.github/workflows/integration-test.yml
.github/workflows/lint.yml

- upgrade actions to a version that use node20 (LTS)

chore: upgrade actions to a version that use node20 (LTS)

---

scripts/github/docker.py

- Send staging images to docker hub

chore: docker hub staging image

---

scripts/github/docker.py

- Change docker hub tag generate on master to "master"

chore: create a master tag on docker hub

---

package-lock.json
package.json
src/services/logger.service.js
src/services/wallets.service.js

- Configure the headless logger on the lib
- Bump lib with latest changes on version v1.12.0

feat: custom logger for lib

---

package-lock.json
package.json

Bumps the version to v0.31.0-rc.1
Related to https://github.com/HathorNetwork/hathor-wallet-headless/pull/482

bump: v0.31.0-rc.1

---

package-lock.json
package.json

bump: v0.31.0

---

__tests__/mark_utxos_selected_as_input.test.js
__tests__/p2sh/tx-proposal-create.test.js
__tests__/p2sh/tx-proposal-melt-tokens.test.js
__tests__/p2sh/tx-proposal-mint-tokens.test.js
__tests__/p2sh/tx-proposal-new-token.test.js
src/api-docs.js
src/controllers/wallet/p2sh/tx-proposal.controller.js
src/controllers/wallet/wallet.controller.js
src/helpers/tx.helper.js
src/routes/wallet/p2sh/tx-proposal.routes.js
src/routes/wallet/wallet.routes.js

- Create a new API to mark utxos as selected for input or unmark them.
- Add an option on the p2sh proposal api to mark utxos as selected for input.

feat: mark inputs as used

---

package-lock.json
package.json

- Sync master branch with release

Chore/sync release v0.31.0

---

package-lock.json
package.json

chore: bump v0.32.0-rc.1

---

package-lock.json
package.json

chore: bump v0.32.0

---

package-lock.json
package.json

- sync release branch from the latest release

sync: release v0.32.0

---

package-lock.json
package.json

chore: bump v0.33.0-rc.1

---

package-lock.json
package.json

bump v0.33.0

---

package-lock.json
package.json

chore: bump v0.34.0-rc.1

---

package-lock.json
package.json

chore: bump v0.34.0

---

__tests__/__fixtures__/settings-fixture.js
__tests__/history-sync.test.js
__tests__/integration/configuration/settings-fixture.js
__tests__/test-utils.js
src/services/wallets.service.js

- Change the default history sync mode to use manual streaming.

feat: use xpub stream as default

---

package-lock.json
package.json

chore: bump package to v0.35.0

---

package-lock.json
package.json

chore: bump v0.35.1

---

__tests__/__fixtures__/http-fixtures.js
__tests__/integration/configuration/bet.py
__tests__/integration/docker-compose.yml
__tests__/integration/nano-contracts.test.js
__tests__/nano-contracts/execute.test.js
__tests__/nano-contracts/history.test.js
__tests__/nano-contracts/oracle.test.js
__tests__/test-utils.js
package-lock.json
package.json
src/api-docs.js
src/controllers/wallet/nano-contracts.controller.js
src/routes/wallet/nano-contracts.routes.js
src/services/fireblocks.service.js
src/services/hsm.service.js

- Add contract id to get oracle signed data api

feat: pass contract_id to oracle signing method

---

package-lock.json
package.json

chore: bump package to v0.36.0

---

package-lock.json
package.json

- Bump package to v0.36.1-rc.1

chore: bump package to v0.36.1-rc.1
