HathorNetwork/hathor-wallet-headless

- README.md
- api-docs.js
- api-key-auth.js
- config.js.template
- index.js
Maybe it closes #3, but we need to discuss it further.
This implementation follows the [Swagger Specification for API Keys](https://swagger.io/docs/specification/authentication/api-keys/).
Before merging:
> feat(auth): Add support for a simple API Key verification

- README.md
- package-lock.json
User EuroLine was having problems loading his wallet. The one loaded in Desktop wallet was different from the one in wallet headless. It seems the problem was the passphrase, that had special chars.
> fix: add urlencode to curl command

- index.js
Adapting send transaction code to use tx mining API. Wallet headless does not give partial feedback to the user of time estimation. It just waits for the tx to be mined, completed and propagated to the network.
> feat: send tx now uses tx mining API

- api-docs.js
- index.js
- package-lock.json
- package.json
There are some features/fixes on this PR:
1. If I receive a `/start` to a key I already have, I stop the old wallet and start a new one. This fixes a bug when sending `/start` many times to the same key/wallet
2. Add optional token parameter  to `/balance`, `/simple-send/tx` and `/send-tx` endpoints
3. Add endpoint to create, mint and melt tokens (`/create-token`, `/mint-tokens`, `/melt-tokens`)
> feat: add POST to create token and token as optional parameters on balance and simple-send-tx

- src/index.js
We used to get `req.query.index` as string, thus when comparing `const index = req.query.index || null`, when `index = '0'` it used to work fine. However, we've added a sanitization and `toInt` protection. After that, `req.query.index` is already an integer and if `index = 0` the comparison does not work.
> fix: fix address generation for index 0

- src/index.js
We already have an issue to add support for multiples API to introduce endpoints that break compatibilities with old endpoints (https://github.com/HathorNetwork/hathor-wallet-headless/issues/120)
Before implementing this we must always keep compatibility with old endpoints and the new lib return for created tokens changed two keys in the transactions.
- We must keep the same return keys for the return of APIs that created transactions.
> feat: map created tx return to keep compatibility with old return APIs

- .dockerignore
- config.js.docker
- It should be possible to set the txMiningUrl by setting the env var `HEADLESS_TX_MINING_URL` in the Docker container
> fix: Allow setting TxMiningUrl using env vars in Docker

- .gitignore
- __tests__/integration/address-info.test.js
- __tests__/integration/balance.test.js
- __tests__/integration/configuration/config.js.template
- __tests__/integration/configuration/test.config.js
- __tests__/integration/create-token.test.js
- __tests__/integration/docker-compose.yml
- __tests__/integration/melt-tokens.test.js
- __tests__/integration/mint-tokens.test.js
- __tests__/integration/send-tx.test.js
- __tests__/integration/simple-send-tx.test.js
- __tests__/integration/transaction.test.js
- __tests__/integration/tx-history.test.js
- __tests__/integration/txLogger.js
- __tests__/integration/utils/test-utils-integration.js
- __tests__/integration/utils/wallet-helper.js
- config.js.template
- jest-integration.config.js
- setupTests-integration.js
This pull request is the second phase of the implementation of Integration Tests on the Hathow Wallet Headless, and expands the scope of #149 .
- The wallets are now instantiated all at once on the `WalletHelper.startMultipleWalletsForTest()` method. This is a performance improvement, since wallet initialization is the most time-consuming process on the integration tests.
- Genesis wallet initialization was removed from the `setupTests-integration.js:beforeAll()` method to use the process above.
An effort was made to make the tests use as little transactions as possible, since transactions are the second slowest process on the tests. As the integration tests use Jest's `--runInBand` configuration, it became possible to use one test's resulting condition as precondition to the next tests. …
> Integration tests: simple send-tx, send-tx, create-tokens, mint and melt tokens

- __tests__/__fixtures__/http-fixtures.js
- __tests__/address.test.js
- __tests__/addresses.test.js
- __tests__/balance.test.js
- __tests__/integration/send-tx.test.js
- __tests__/integration/utils/wallet-helper.js
- __tests__/send-tx.test.js
- __tests__/test-utils.js
- __tests__/tx-history.test.js
- __tests__/utxo.test.js
- src/index.js
The feature to `send-tx` querying by filter address was only working for HTR tokens, and would have wrong behaviors when any of the outputs had a custom token.
- A transaction must be successful with input address filter query and custom tokens, as described in #151
> Fix issue when user filters UTXOs by address query and custom tokens

- package-lock.json
- package.json
- Upgrade `@hathor/wallet-lib` to v0.33.1
> chore: upgrade wallet lib v0.33.1

- __tests__/integration/utxo-filter.test.js
- src/routes/wallet/wallet.routes.js
The parameter to filter by available utxos was incorrectly configured on the application routes.
It was renamed on the routes and on the integration test file. The docs were correct already.
- The parameter to filter only available UTXO's should work according to [the docs](https://wallet-headless.docs.hathor.network/#/paths/~1wallet~1utxo-filter/get)
> fix: utxo-filter parameter only-available

- __tests__/__fixtures__/feature-fixture.js
- __tests__/create-nft.test.js
- __tests__/send-tx.test.js
- src/constants.js
- src/routes/wallet/wallet.routes.js
- APIs that create data script outputs should have maximum length of data string. For now, we have only send-tx and create-nft.
> feat: add length max for data script outputs

- config.js.docker
The wallet was not working when using docker because we are importing the config with `require` and the config is being exported with `export default config;`.
At first I was doing the solution to refactor all `require` to use `import`, so we wouldn't need to care about it. After I changed in all internal modules this import (controllers, middlewares, routes, ...), I got an error that we can't have `import` in modules that have `module.exports`. Given that we need this fix and the refactor would need to be bigger, I decided to go back to the `config.js.docker` file and change `export default config;` to `module.exports = config;`.
This way, the config for docker is exported the same way as the normal config, where we use `module.exports = {` and the whole config object.
- Wallet headless …
> fix: using module.exports instead of export default

- .github/workflows/docker.yml
- Push the Docker image to AWS ECR
- Use newest versions of the Docker actions for Github
Test execution: https://github.com/HathorNetwork/hathor-wallet-headless/runs/7339655008?check_suite_focus=true
> ci: push docker image to AWS ECR

- Dockerfile
Newer docker images (since v0.13.0) have a bug when running commands that are inside `scripts` folder because it was recently created. We must copy this folder to the docker image as we do with the `src` folder.
- Command `npm run generate_words` should work using docker.
> fix: add scripts folder to docker image folder

- __tests__/start.test.js
- src/api-docs.js
- src/controllers/index.controller.js
- src/helpers/constants.js
- We should add an `errorCode` field in the response of the `/start` endpoint, so the client knows that the error happened because the wallet was already started
> feat: add errorCode in the response for when some wallets are already started

- .github/workflows/docker.yml
- RELEASING.md
- src/api-docs.js
- We should push Docker images to ECR tagged with `staging-` tags when commits are made to master
- We should have a release guide
> ci: push staging images / create release guide

- __tests__/__fixtures__/http-fixtures.js
- __tests__/configuration_string.test.js
- __tests__/integration/configuration-string.test.js
- __tests__/integration/create-nft.test.js
- __tests__/integration/create-token.test.js
- __tests__/integration/utils/test-utils-integration.js
- __tests__/test-utils.js
- src/api-docs.js
- src/controllers/index.controller.js
- src/controllers/wallet/wallet.controller.js
- src/index.js
- src/routes/index.routes.js
- Add the token configuration string in the response of the endpoints to create token and create NFT.
- Add new endpoint to get a configuration string of a given token from its uid.
- Add tests for the new endpoint and the new response field in old APIs.
- Update API docs.
> feat: add new endpoint to return token configuration string

- package-lock.json
- package.json
- src/api-docs.js
- Bump wallet lib to v0.42.1
- Bump headless to v0.19.1
> chore: bump wallet lib to v0.42.1

- __tests__/send-tx.test.js
- src/controllers/wallet/wallet.controller.js
If debug is enabled (sending `debug=true` on the request body) for the `/wallet/send-tx` api and we have an error sending the transaction the error will not be logged since `logger.debug` is used, but it is not a function.
This has been attributed to how we import the logger module, when using CommonJS (require syntax) the module does not export some methods (debug, info, etc.). Using ES6 (import syntax) seems to work
- Import logger module with `import` instead of require
> fix: import logger module with ES6 syntax

- __tests__/__fixtures__/http-fixtures.js
Timelock for fixtures was set for `1675256215` which is february first of 2023, this was making the tests fail so the fixture was updated with a timestamp on the year 3000.
> fix: timelock too soon

- __tests__/address-info.test.js
- __tests__/atomic-swap/get-my-signatures.test.js
- __tests__/atomic-swap/locked-utxos.test.js
- __tests__/atomic-swap/p2sh.test.js
- __tests__/atomic-swap/sign-and-push.test.js
- __tests__/atomic-swap/sign.test.js
- __tests__/create-nft.test.js
- __tests__/create-token.test.js
- __tests__/decode.test.js
- __tests__/integration/address-info.test.js
- __tests__/integration/readonly-wallet.test.js
- __tests__/melt-tokens.test.js
- __tests__/mint-tokens.test.js
- __tests__/multisig-pubkey.test.js
- __tests__/p2sh/tx-proposal-create.test.js
- __tests__/p2sh/tx-proposal-get-my-signatures.test.js
- __tests__/p2sh/tx-proposal-sign-and-push.test.js
- __tests__/p2sh/tx-proposal-sign.test.js
- __tests__/push-tx-hex.test.js
- __tests__/send-tx.test.js
- __tests__/simple-send-tx.test.js
- __tests__/start.test.js
- __tests__/transaction.test.js
- __tests__/tx-proposal/add-signatures.test.js
- __tests__/tx-proposal/build-tx.test.js
- __tests__/tx-proposal/get-wallet-inputs.test.js
- __tests__/tx-proposal/getInputData.test.js
- src/controllers/index.controller.js
closes: https://github.com/HathorNetwork/on-call-incidents/issues/99
- We should have the 'success' field in the response body of the /start API, when someone tries to start an already started wallet id. It was removed in past PRs.
- We should make sure our tests will fail in case we remove the `success` field again in some response. Since we were using `toBeFalsy` and `toBeTruthy` to test the API response, the error wouldn't be caught by the tests (because `undefined` is falsy)
> fix: 'success' field was missing in one response body

- __tests__/atomic-swap/atomic-swap-service.test.js
- __tests__/atomic-swap/service.test.js
- __tests__/atomic-swap/tx-proposal-create.test.js
- src/controllers/wallet/atomic-swap/tx-proposal.controller.js
- src/controllers/wallet/wallet.controller.js
- src/routes/wallet/atomic-swap/tx-proposal.routes.js
- src/services/atomic-swap.service.js
- src/services/wallets.service.js
Creates the infrastructure described on design HathorNetwork/rfcs#50 to keep track of the proposals being listened by a wallet, also adapting the existing `create` endpoint.
- Implement the listened proposals structure
- The existing `create` route should add proposals to it
- Implement the `list` and `remove` endpoints
Note: the `fetch`, `register` and `update` endpoints will be implemented in separate PRs, since they involve interacting with the atomic swap service.
> feat: Listened proposals

- __tests__/integration/create-nft.test.js
- __tests__/integration/create-token.test.js
- package-lock.json
- package.json
- src/api-docs.js
- src/controllers/wallet/wallet.controller.js
- src/routes/wallet/wallet.routes.js
- Add parameters in the create token endpoint to choose whether the user wants to create mint/melt authorities, define the addresses to where they will be sent, and if it allows external addresses.
- Add parameters in the create nft endpoint to define the addresses to where these authorities will be sent and if it allows external addresses.
> feat: add parameter to create token and create nft endpoints to set authority addresses

- __tests__/atomic-swap/tx-proposal-create.test.js
- src/controllers/wallet/atomic-swap/tx-proposal.controller.js
- Passing an invalid `partial_tx` to `/wallet/atomic-swap/tx-proposal` should result in a treated HTTP response with the error description as a message
> fix: Handling invalid `partial_tx` input errors

- Dockerfile
During the release of the last version we found out the docker build was failing due to missing dependencies.
- Include build deps when installing deps on docker
> chore: install build deps

- scripts/github/docker.py
- Match versions with multiple digits
> fix: match more than 1 digit on versions

- scripts/github/docker.py
- Deprecate set-output command ([reference](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
> chore: deprecate set-output command

- scripts/github/docker.py
- Add missing separator for github outputs
> chore: add missing endl in github output

- __tests__/integration/multisig.test.js
- __tests__/integration/utils/test-utils-integration.js
Issue: https://github.com/HathorNetwork/hathor-wallet-headless/issues/292
- Wait multisig transaction before continuing test to prevent out of funds error
> tests: wait for multisig tx to arrive before continuing the test

- __tests__/decode.test.js
- __tests__/integration/atomic-swap.test.js
- __tests__/integration/multisig.test.js
- __tests__/integration/utils/test-utils-integration.js
- __tests__/integration/utils/wallet-helper.js
- src/api-docs.js
- src/controllers/wallet/wallet.controller.js
- test: implement e2e tests for create, mint, melt and decode endpoints
Depends on:
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/309
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/312
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/313
- https://github.com/HathorNetwork/hathor-wallet-headless/pull/315
Closes: https://github.com/HathorNetwork/hathor-wallet-headless/issues/316
> test: add e2e tests to multisig extension endpoints

- __tests__/decode.test.js
- __tests__/integration/multisig.test.js
- src/api-docs.js
- src/controllers/wallet/wallet.controller.js
- Add mine attribute in the body of output payaload
- Remove mine from decoded attribute in the output payload
This change was required in the [design review](https://github.com/HathorNetwork/rfcs/pull/57). See the [thread](https://github.com/HathorNetwork/rfcs/pull/57#discussion_r1275348704).
> feat: add mine in the output body

- package-lock.json
- package.json
> chore: bump wallet-lib v1.0.1

- __tests__/decode.test.js
- __tests__/integration/multisig.test.js
- src/controllers/index.controller.js
- src/controllers/wallet/wallet.controller.js
- When the spent transaction is not from our wallet the token field would come as `undefined` and `JSON.stringify` would remove the token property from the decoded transaction.
> feat: add token to decode when the spent tx is not ours

- .github/workflows/integration-test.yml
- __tests__/integration/configuration/test.config.js
- __tests__/integration/utils/test-utils-integration.js
- package.json
- setupTests-integration.js
- We must mine at least one block before starting the integration tests, so the genesis reward is unlocked.
- Add timeout in the method to wait for next block.
- The unit tests were running in parallel and they started to fail because of that. A deeper investigation on this matter must be done but in this PR I decided to just start running them serial, so everything is tested and works fine. A issue was created to handle this: https://github.com/HathorNetwork/hathor-wallet-headless/issues/355
> tests: wait first block in integration tests to release genesis reward

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/feature.md
- .github/PULL_REQUEST_TEMPLATE/release.md
- .github/PULL_REQUEST_TEMPLATE/release_candidate.md
- Create the new pull request templates to follow the new release process
We are using the features described in the [github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request) to create a PR template chooser and allow multiple PR templates on the github web ui.
These templates can also be used by name with the github cli or api (in a future integration) if needed.
> docs: pull request templates for new release process

- __tests__/__fixtures__/http-fixtures.js
- __tests__/__fixtures__/settings-fixture.js
- __tests__/healthcheck.test.js
- __tests__/test-utils.js
- package-lock.json
- src/api-docs.js
- src/controllers/healthcheck/healthcheck.controller.js
- src/helpers/constants.js
- src/helpers/healthcheck.helper.js
- src/routes/healthcheck/healthcheck.routes.js
- src/routes/index.routes.js
- src/services/healthcheck.service.js
Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/579
- Create a new `/health` endpoint to return information about the health of the wallets and the connected components (tx-mining-service, hathor-core).
Note: There is an unfinished TODO because we are still developing a new `/health` endpoint on hathor-core as well. It will be solved in a future PR to use the new endpoint there when it's ready.
Note: The tests are failing because they depend on the wallet-lib changes.
> feat: new healthcheck endpoint

- __tests__/integration/send-tx.test.js
- src/api-docs.js
- src/routes/wallet/wallet.routes.js
A use case needs to create transactions with timelock using the headless.
- Add support for timelock in the `send-tx` API.
> feat: add support for timelock in the send tx API

- .github/workflows/apidocs-upload.yml
- package.json
Finishes implementation of the [Api Docs CI](https://github.com/HathorNetwork/rfcs/blob/master/projects/hathor-wallet-headless/api-docs-ci.md) RFC.
When a commit on the `release` branch receives a valid version `tag`, this workflow automatically uploads the generated apidocs to the official apidocs website.
- Automates the updating of the official [Headless Wallet apidocs](https://wallet-headless.docs.hathor.network/)
Instead of creating a whole new workflow, we could have reused the existing `apidocs.yml` from #362 to generate the Api-Docs and lint them. The only steps left would be caching the results and uploading them to S3. The different approaches to this had some drawbacks:
We could add the version validation to the `lint` job and upload the S3 right there. However this would make …
> feat: Upload the api-docs on CI

- .github/workflows/apidocs-upload.yml
The `upload api-docs` script created on #364 had issues with the context of its environment variables not being accessible when needed.
- Correctly uploads the `api-docs` to our documentation environment ( [evidence](https://github.com/HathorNetwork/hathor-wallet-headless/actions/runs/7467110975/job/20355501924) )
- Scope changed from `env` to `needs`, that is available inside an `if` clause
- Fixes the `ref` retrieval, obtaining it from a bash environment variable instead
- Changed workflow name to increase clarity on the GitHub actions tab
- Upload to `dev` by default, safeguarding the production environment
> fix: Upload `api-docs` workflow

- config.js.docker
We shouldn't get the following error when running the Docker image (introduced in https://github.com/HathorNetwork/hathor-wallet-headless/pull/376):
```
/usr/src/app/dist/config.js:53
throw new Error(`Invalid boolean parameter for ${name}. Received ${param}.`);
^
Error: Invalid boolean parameter for consider_healthcheck_warn_as_unhealthy. Received true.
at getBooleanParam (/usr/src/app/dist/config.js:53:9)
at Object.<anonymous> (/usr/src/app/dist/config.js:82:39)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at …
```
> fix: Docker env var type

- __tests__/integration/transaction.test.js
We have frequently seen the error below in the confirmation blocks integration tests.
```
● transaction routes › test confirmation blocks
expect(received).not.toBeNull()
Received: null
77 |       const txData2 = await TestUtils.getFullNodeTransactionData(txId);
78 |       firstBlockHeight = txData2.meta.first_block_height;
> 79 |       expect(firstBlockHeight).not.toBeNull();
|                                    ^
80 |     }
81 |
82 |     await TestUtils.waitNewBlock(firstBlockHeight);
at Object.<anonymous> (__tests__/integration/transaction.test.js:79:36)
at runMicrotasks (<anonymous>)
```
The best explanation is described in the code. A miner might be mining a new block really fast, then the block template is not updated with the new tx as a parent, so even with a new block, the tx is …
> tests: fix error when metadata of tx was still not updated

- src/controllers/index.controller.js
- src/helpers/wallet.helper.js
- src/services/wallets.service.js
On the comment https://github.com/HathorNetwork/hathor-wallet-headless/pull/356#discussion_r1448223715 it was suggested that the wallet starting procedure should be centralized in a service function.
This PR extracts the wallet starting process so that it can be called from different conditions ( namely: HSM readonly wallets or conventional wallets ).
- The wallet starting process should be extracted to a service function
> Refactor: Wallet Start service function

- __tests__/__fixtures__/feature-fixture.js
- src/constants.js
- src/controllers/wallet/atomic-swap/tx-proposal.controller.js
- src/controllers/wallet/p2sh/tx-proposal.controller.js
- src/controllers/wallet/tx-proposal/tx-proposal.controller.js
- src/helpers/wallet.helper.js
Closes #246 
- Moves the default `pin` and `password` hardcoded strings to the `constants.js` file
> refactor: Moves default `pin` to constants

- package-lock.json
- package.json
- Upgrades `express`
The initial expectation was to also upgrade the `express-validator` dependency within this PR, with its major update from `v6` to `v7`. I followed the [migration guide](https://express-validator.github.io/docs/migration-v6-to-v7) to solve the [breaking changes](https://github.com/express-validator/express-validator/releases/tag/v7.0.0), but ended up with some workarounds that were not sounding very correct ( ex.: declaring that the minimum length of an array is `2` so that it would validate that the array should not be empty )
Upon a closer look I found that there are some open issues about array validation that may demand a breaking change soon in this dependency ( see https://github.com/express-validator/express-validator/pull/1280 ).
Since the immediate benefit of …
> chore: Upgrades `express` and related

- .github/workflows/apidocs-upload.yml
The environment variable for the _upload_ step was being retrieved from the incorrect source.
- Fixes the api-docs HTML upload for official releases
> fix: HTML upload for release environment

- __tests__/integration/plugins/integration_test_plugin.js
- __tests__/integration/plugins/plugin-events.test.js
This PR adds integration tests for the Plugins, validating their event handling behavior on a live blockchain.
The initial expectation here, as described on #269,  was to test the actual plugin files packed with the Headless wallet. However, that would require new test workflows, with their configuration files and dependencies to be added, thus increasing the complexity of the tests suite.
A decision was made to restrict the scope to only testing the event bus on the integration environment: this validates that all events are sent in the correct moment with the correct data. An exception is made to the _New Best Blockchain_ event that is still untested because it requires a more complex setup.
This covers the gap of having integration tests for the plugins and only requires one test file …
> test: Plugin events integration tests

- .gitignore
- CustomEnvironment.js
- __tests__/integration/address-info.test.js
- __tests__/integration/balance.test.js
- __tests__/integration/configuration-string.test.js
- __tests__/integration/create-nft.test.js
- __tests__/integration/create-token.test.js
- __tests__/integration/melt-tokens.test.js
- __tests__/integration/mint-tokens.test.js
- __tests__/integration/plugins/integration_test_plugin.js
- __tests__/integration/send-tx.test.js
- __tests__/integration/simple-send-tx.test.js
- __tests__/integration/transaction.test.js
- __tests__/integration/tx-history.test.js
- jest-integration.config.js
- package-lock.json
- package.json
- setupTests-integration.js
Since Jest v27, the official runner for that framework is no longer `jasmine2`, but [`jest-circus`](https://github.com/jestjs/jest/tree/main/packages/jest-circus#overview). Migrating from one to the other required a few changes to the code to run correctly:
- Fetching the test name to feed the precalculated wallets manager required the construction of a _Custom Environment_. (https://github.com/HathorNetwork/hathor-wallet-headless/pull/412/commits/f1173e6cc22dd6b542353a8979e21dec25d9ef49)
- The stricter _circus_ runner threw an error instead of a warning when the _Plugins_ integration test tried to remove a listener without the function reference. (https://github.com/HathorNetwork/hathor-wallet-headless/pull/412/commits/ceddd374781ff91bd8ad3b95ba9c0e66dc92b08b)
- The stricter _circus_ …
> chore: Upgrades `jest`

- package-lock.json
- All dependencies that can be automatically updated by `npm audit fix` should be updated.
All direct dependencies, those described by our `package.json`, have already been updated to their latest versions recently. The ones proposed by this PR are dependencies _of those dependencies_, and are being updated because of security alerts related to them ( see advises below ).
Those updates respect the requirements of their parent dependencies according to _semver_. For example, `color` requires `color-string: "^1.5.2"`. So `color-string` is being updated to `1.9.1` to respect this restriction.
- Color String
- [Regular Expression Denial of Service (ReDOS)](https://github.com/advisories/GHSA-257v-vj4p-3w2h)
- SemVer
- [Regular Expression Denial of …
> Chore: `npm audit` fixes

- .github/workflows/main.yml
Codecov's upload task on CI broke, it used to be unstable so we suspected that was the case but apparently it is now required to use a token.
- Add a secret token to the repo's settings
- Add CI config to expose the token to codecov's upload task
> fix: add codecov token in secret to do codecov upload

- config.js.docker
- config.js.template
- src/controllers/fireblocks/fireblocks.controller.js
- src/services/fireblocks.service.js
- src/settings.js
The fireblocks secret is a PEM encoded private key, which means it is a multiline file.
Since our config is an object I encoded the file contents in a single line with `\n` separators where the line breaks should be.
This approach works for the config file (i.e. running locally on the repo), but it did not work consistently in docker.
Docker would escape the `\n` in the string making them `\\n` and the content unusable.
There is a way to use multiline environment variable but it only works on older versions of docker.
To solve this I decided to actually use a file when running on docker and the config would be the file path.
Since the file needs to be in the container it can be mounted as a volume, which works when running with docker, docker-compose and Kubernetes.
The example command …
> chore: configure fireblocks secret in docker

- __tests__/integration/readonly-wallet.test.js
- src/controllers/index.controller.js
- src/controllers/wallet/tx-proposal/tx-proposal.controller.js
The [read only wallets tutorial](https://docs.hathor.network/tutorials/headless-wallet/read-only-wallets/) is not working in the latest headless wallet version. The reason for that is because we are creating a tx proposal without weight/timestamp, which is needed by the transaction mining service.
The tutorial was written using version 0.19.2, which used [wallet lib v0.42.1](https://github.com/HathorNetwork/hathor-wallet-headless/blob/v0.19.2/package.json#L15).
The tx proposal used to call [`prepareDate` method](https://github.com/HathorNetwork/hathor-wallet-headless/blob/v0.19.2/src/controllers/wallet/tx-proposal/tx-proposal.controller.js#L53), which called [completeTx method](https://github.com/HathorNetwork/hathor-wallet-lib/blob/v0.42.1/src/transaction.js#L717) that filled the weight …
> fix: add tx timestamp and weight in the tx proposal API because it's needed for the tx mining service

- SECURITY.md
Update the "security" document link to point to the new security page on the main Hathor Network website.
Updated link from:
https://docs.hathor.network/references/besides-documentation#security
To:
https://hathor.network/bug-bounty/
> docs(security): update link to bug bounty program

- .github/workflows/integration-test.yml
- .github/workflows/main.yml
- Fixes warnings about the CI workflow actions to use NodeJS 20
- Forces an error on CI if CodeCov fails, to improve our understanding of its errors
The `upload-artifact` and `gh-docker-logs` actions will be upgraded in a future moment, as they have breaking changes that will need more attention to adapt to.
The intermittent errors we're having of not finding the secret token on CodeCov seems to have been fixed by the latest action version. Recent issues about this problem were found on [1463](https://github.com/codecov/codecov-action/issues/1463) and [1425](https://github.com/codecov/codecov-action/issues/1425) with no definitive solution.
> chore: Upgrades CI workflow actions

- config.js.docker
This PR extracts a fix from https://github.com/HathorNetwork/hathor-wallet-headless/pull/450, so I just copied the description from there, which was good enough:
- Fixing multisig param types: when deploying on some cloud environments (such as GCP Cloud Run), the **_multisig_seed_${x}_max_signatures_** and **_multisig_seed_${x}_num_signatures_** are threated as strings, not integers. When starting the multisig, the comparison made with this params is a exact on (  "===") so it fails. By parsing the params before we can avoid that.
src/controllers/index.controller.js Ln 100-101:
```
const mconfig = config.multisig[multisigKey];
console.log('mconfig', mconfig);
if (!(mconfig
&& (mconfig.total && mconfig.numSignatures && mconfig.pubkeys)
&& (mconfig.pubkeys.length === mconfig.total)
&& …
```
> fix: multisig config on Docker

- .eslintrc
- src/app.js
- src/controllers/fireblocks/fireblocks.controller.js
- src/controllers/hsm/hsm.controller.js
- src/controllers/index.controller.js
- src/controllers/wallet/atomic-swap/tx-proposal.controller.js
- src/controllers/wallet/p2sh/tx-proposal.controller.js
- src/controllers/wallet/tx-proposal/tx-proposal.controller.js
- src/controllers/wallet/wallet.controller.js
- src/helpers/tx.helper.js
- src/helpers/wallet.helper.js
- src/index.js
- src/logger.js
- src/middlewares/logger.middleware.js
- src/routes/index.routes.js
- src/services/fireblocks.service.js
- src/services/hsm.service.js
- src/services/logger.service.js
- src/services/wallets.service.js
- Include the wallet-id on the logs where possible
> feat: include the wallet-id responsible for the log

- __tests__/__fixtures__/http-fixtures.js
- __tests__/integration/docker-compose.yml
- __tests__/integration/nano-contracts.test.js
- __tests__/test-utils.js
- package-lock.json
- package.json
- Update wallet lib to v1.10.0
- Update tests for new expected type of params for new lib version.
- Update blueprint info url ( See https://github.com/HathorNetwork/hathor-wallet-lib/pull/734 )
> feat: update wallet lib to v1.10.0

- __tests__/__fixtures__/ws-fixtures.js
- __tests__/history-sync.test.js
- __tests__/mark_utxos_selected_as_input.test.js
- package-lock.json
- package.json
- scripts/convert-docs.js
- src/helpers/tx.helper.js
- Bump wallet-lib to latest version
- Use wallet facade method to mark utxos as selected_as_input instead of storage method.
> feat: use wallet facade method to mark inputs as selected

- __tests__/integration/nano-contracts.test.js
- src/api-docs.js
- src/controllers/wallet/nano-contracts.controller.js
- src/routes/wallet/nano-contracts.routes.js
- Add `before` query parameter to the nano contract history API.
- Add `block_hash` and `block_height` query parameters to the nano contract state API.
> feat: add missing parameters in nano contract API

- src/controllers/wallet/atomic-swap/tx-proposal.controller.js
- src/helpers/lock.helper.js
- src/lock.js
- All HSM wallets should share the same lock
This is due to a limit on the HSM SDK that trying to start a second connection would fail.
So the wallets should only have 1 connection open at any given time, which is done with the lock system.
> hsm share lock

- Makefile
- docs/multisig-wallets.md
- scripts/get_multisig_xpub_from_seed.js
- We should be able to run `make multisig_xpub_from_seed seed="<seed words>"` to get a multisig xpub from seed
- Some people were mistakenly using `make xpub_from_seed` for this.
- It will make it easier to generate a multisig xpub in automated environments
> feat: script to get multisig xpub from seed easily

- __tests__/plugins/child.test.js
- __tests__/plugins/debug_plugin.test.js
- __tests__/plugins/rabbitmq_plugin.test.js
- __tests__/plugins/sqs_plugin.test.js
- __tests__/plugins/ws_plugin.test.js
- docs/plugins.md
- src/index.js
- src/plugins/child.js
- src/plugins/hathor_debug.js
- src/plugins/hathor_rabbitmq.js
- src/plugins/hathor_sqs.js
- src/plugins/hathor_websocket.js
- Events containing BigInt fields should be correctly sent to the plugins process
- The plugins should all serialize data in a way that supports BigInt
> fix: support for BigInt on plugins

- .github/workflows/apidocs-upload.yml
- .github/workflows/apidocs.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/main.yml
ubuntu 20 was deprecated as a runner and some actions that use it are not running anymore.
- Update runners to use ubuntu latest
> chore: update action runner to ubuntu-latest

- __tests__/__fixtures__/http-fixtures.js
- __tests__/test-utils.js
- package-lock.json
- package.json
- src/controllers/wallet/wallet.controller.js
Get mining info API always returns height 0 on PoA side-dags and not the best chain height.
- Get best chain height from features API.
> feat: get best block height from features API

- package-lock.json
- package.json
> chore: bump wallet-lib v2.3.1
